# Generated by Django 3.1.3 on 2021-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210118_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
