# Generated by Django 3.1.3 on 2021-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
